sudo: false
language: node_js
services:
 - elasticsearch
node_js:
  - 0.10
  - 0.12
  - 4.4
  - 5.8
matrix:
    allow_failures:
        - node_js: 4.4
        - node_js: 5.8
env:
 global:
   - CXX=g++-4.8
 matrix:
   - TEST_SUITE=test
   - TEST_SUITE=integration
script: "npm run $TEST_SUITE"
addons:
 apt:
   sources:
     - ubuntu-toolchain-r-test
   packages:
     - g++-4.8
